### ISSUE TITLE
Alternative map bug

### ISSUE THREAD

**Issue by RonDallas** [LLDM-Doom-Modding/ZChecker#3]
![35cf4f6b79fd3f31](https://github.com/LLDM-Doom-Modding/ZChecker/assets/32035822/ecf0336c-c790-4c05-b7bb-187112a47aee)
![ef49789e874a4265](https://github.com/LLDM-Doom-Modding/ZChecker/assets/32035822/6e9fadee-c788-4089-a745-67abd5068533)

**Comment by MorthimerMcMare** [comment]
Sorry, forgot about issues...
Found it. Will be fixed in the next week.

**Comment by MorthimerMcMare** [comment]
Commit da06012446dda0c2fca89ce228dd8b709474853e. Found and fixed:

![изображение](https://github.com/LLDM-Doom-Modding/ZChecker/assets/34414934/a8c0a0f5-1d98-4d0f-b4c6-6a65a7cfbc0a)
![изображение](https://github.com/LLDM-Doom-Modding/ZChecker/assets/34414934/d14ba8e4-46f9-4c04-bca5-5f6f336da0d8)
