### ISSUE TITLE
ZChecker v0.87 is broken in the latest version of GZDoom

### ISSUE THREAD

**Issue by GeminiCrafterMan** [LLDM-Doom-Modding/ZChecker#4]
```
Script error, "ZChecker_v0.87.pk3:zscript/core/zcmapscripts.zsc" line 55:
Expression must be a modifiable value
Script error, "ZChecker_v0.87.pk3:zscript/core/zcmapscripts.zsc" line 56:
Expression must be a modifiable value
Script error, "ZChecker_v0.87.pk3:zscript/core/zcmapscripts.zsc" line 57:
Expression must be a modifiable value
Script error, "ZChecker_v0.87.pk3:zscript/core/zcmapscripts.zsc" line 58:
Expression must be a modifiable value
Script error, "ZChecker_v0.87.pk3:zscript/core/zcmapscripts.zsc" line 59:
Expression must be a modifiable value
```
I'm not sure what this is about, but since ZChecker was written in DECORATE rather than ZScript, merely rolling back the ZScript version wouldn't fix this.

**Comment by MorthimerMcMare** [comment]
@GeminiCrafterMan, thank you for the feedback! Commit https://github.com/LLDM-Doom-Modding/ZChecker/commit/a54e42bce8fb50c8982c5728498118c1eda232cd should fix the bug. I think it's better to upload the bugfix to the main page.

![image](https://github.com/LLDM-Doom-Modding/ZChecker/assets/34414934/9548b3f4-98b4-4c2e-929e-249d277a899f)

> I'm not sure what this is about, <...>

In GZDoom 4.12.x, the `FColormap` fields became readonly; ZChecker uses them as a convenient storage cell...

> <...> since ZChecker was written in DECORATE rather than ZScript, <...>

Not at all: DECORATE isn't used in the ZChecker :) . It is just developed to be useful for the modders on DECORATE, ZScript and, as far as possible, ACS.

**Comment by GeminiCrafterMan** [comment]
...How in the world did I not see that.
Anyway, glad it's fixed now -- finally I can autoload it again :)

**Comment by MorthimerMcMare** [comment]
New release: "[v0.87_bugfix_gzdoom_4.12_compatibility](https://github.com/LLDM-Doom-Modding/ZChecker/releases/tag/v0.87_bugfix_gzdoom_4.12_compatibility)".
