### ISSUE TITLE
Don`t work with Lithium[Bug] 

### ISSUE THREAD

**Issue by RonDallas** [LLDM-Doom-Modding/ZChecker#5]
### Bug description

Try to start Lithium with zchecker, and it`s crused.
![image](https://github.com/user-attachments/assets/31ecd617-8bff-4de9-9ec9-79b19f0b1706)

### ZChecker project version

ZChecker_v0.87

### Engine version

GZDoom 4.12.1/VKDoom

**Comment by MorthimerMcMare** [comment]
Seems like you're using the slightly outdated version of the project (see issue https://github.com/LLDM-Doom-Modding/ZChecker/issues/4). Try to download the https://github.com/LLDM-Doom-Modding/ZChecker/releases/tag/v0.87_bugfix_gzdoom_4.12_compatibility. Is it working?

**Comment by RonDallas** [comment]
Check the last version (ZChecker_v0.87b_bugfix.pk3). Have this
![image](https://github.com/user-attachments/assets/3a30d89e-eeeb-4c3a-bdba-3a2e90b1ac06)

**Comment by MorthimerMcMare** [comment]
As far as I see, the error is in the Lithium:
![image](https://github.com/user-attachments/assets/2d9b674f-67e2-4212-ae53-1c73e5408e86)

Lithium tries to create an actor in the `PostBeginPlay()` which uses some external data, but ZChecker, which spawns all actors at once, cannot directly check such usage for each of them (it's the engine limitation). I can suggest you to fix the error in the Lithium source code adding the elementary check expression... I'll help if necessary.

Closer to the ZChecker v1.0, I want to create a semi-automatic subsystem to get rid of the mess: problematic actors will be excluded from the spawn list right after their first crash.

**Comment by MorthimerMcMare** [comment]
> That work. But now i can`t go to Everything map. Also, in the menu command i cant go to alternative map.

You can use the built-in `listmaps` console command to show (obviously) the list of all loaded maps. So, the name of the alternative map is "`EVERYTHING_ALTERNATIVE`".
![image](https://github.com/user-attachments/assets/66884b70-d6b3-4f0d-bf82-f217525dfe57)

Anyway, you're better use the `zcev map` and `zcev map2` ZChecker commands, they are shorter and, in my opinion, easier to remember:
![image](https://github.com/user-attachments/assets/ed1b8c78-ef66-48c3-af1f-0e3539f93978)

**Comment by MorthimerMcMare** [comment]
Misread about warping to the Alternative Everything map. Should be fixed in the https://github.com/LLDM-Doom-Modding/ZChecker/commit/11e9944d927e222238a82edb8e7fa33d266fbf6d.
